spring:
  profiles:
    active: local # 개발환경
    group:
      local: local, common
      blue: blue, common
      green: green, common 

server:
  env: blue

---
# 로컬일 때 이쪽으로 넘어온다 

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8086
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8086
  address: 0.0.0.0


serverName: blue_server

---

spring:
    config:
      activate:
        on-profile: green

server:  
    port: 8087
    address: 0.0.0.0


serverName: green_server

---